-- DROP VSEH TABEL
-- Vrstni red: najprej tabele z FK, nato tiste, ki jih referenced
-- CASCADE CONSTRAINTS odstrani vse FK ki kazejo na tabelo
-- PURGE preskoči koš (recycle bin)

-- 9) ZALOGA
DROP TABLE mes_zaloga_trajna  CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_zaloga         CASCADE CONSTRAINTS PURGE;

-- 8) POSTAVKA RAČUNA
DROP TABLE mes_postavka_racun CASCADE CONSTRAINTS PURGE;

-- 7) HRENOVKE
DROP TABLE mes_izvor_hrenovk  CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_hrenovke_serija CASCADE CONSTRAINTS PURGE;

-- 6) SERIJE
DROP TABLE mes_serija_prasic  CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_serija_vnos    CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_serija         CASCADE CONSTRAINTS PURGE;

-- 5) PRAŠIČI / KLANJE
DROP TABLE mes_klanje_prasic  CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_klanje         CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_prasic         CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_prasic_skupina CASCADE CONSTRAINTS PURGE;

-- 4) PRODAJA
DROP TABLE mes_racun          CASCADE CONSTRAINTS PURGE;

-- 3) NABAVA
DROP TABLE mes_postavka_dobave CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_dobava          CASCADE CONSTRAINTS PURGE;

-- 2) PARTNERJI
DROP TABLE mes_stranka        CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_dobavitelj     CASCADE CONSTRAINTS PURGE;

-- 1) ŠIFRANTI
DROP TABLE mes_cena_izdelka   CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_izdelek        CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_metoda_placila CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_posta          CASCADE CONSTRAINTS PURGE;
DROP TABLE mes_merilna_enota  CASCADE CONSTRAINTS PURGE;
